USE minnesvart_db;

INSERT INTO adventures (name, description, image, longitude, latitude) VALUES 
("Snoqualmie Falls Trail", "This iconic waterfall is accessible to all! This trail has a unique feature in which there is a parking lot at each side of the trail, and both show off the majesty of Snoqualmie Falls and the Salish Lodge. If you are a fan of Twin Peaks, these falls are featured in the intro on every episode. Here's your chance to see it up close and personal.", "https://media.gettyimages.com/photos/snoqualmie-falls-in-fall-picture-id518674788?k=6&m=518674788&s=612x612&w=0&h=YXLkP9FvORX_5cQ9OrVbFpG_RqF-R3HfX3TLIZlU4Do=", 47.5417, -121.8377, 1),
('Mount Rainier', 'Mount Rainier, also known as Tahoma or Tacoma, is a large active stratovolcano in the Cascade Range of the Pacific Northwest, located in Mount Rainier National Park about 59 miles south-southeast of Seattle.','https://upload.wikimedia.org/wikipedia/commons/e/eb/Mount_Rainier_from_west.jpg', 46.8540, -121.7250, 1),
('Olympic National Park', 'Olympic National Park is an American national park located in the State of Washington, on the Olympic Peninsula. The park has four regions: the Pacific coastline, alpine areas, the west side temperate rainforest and the forests of the drier east side. Within the park there are three distinct ecosystems which are subalpine forest and wildflower meadow, temperate forest, and the rugged Pacific coast. President Theodore Roosevelt originally designated Mount Olympus National Monument on 2 March 1909.', 'https://t0.gstatic.com/images?q=tbn:ANd9GcSh0loZEtkB6ycXzxJ08W9ur0lnsfs4pgHgmmmrZm-rJAvhH8kGmMZB6t6NulbWwoSNgqSGji1DEexVIfYYdb-Q7g', 47.8810, -123.4970, 1 ),
('Hoh Rain Forest Visitor Cente', 'Hoh Rainforest is located on the Olympic Peninsula in the Pacific Northwest. It is located in western Washington state, and is one of the largest temperate rainforests in the U.S. Within Olympic National Park, the forest is protected from commercial exploitation. This includes 24 miles of low elevation forest 394 to 2,493 feet along the Hoh River. The Hoh River valley was formed thousands of years ago by glaciers.', 'https://lh5.googleusercontent.com/proxy/nijRmspUGAid98hd3ABVAn4ztNXNrk_DeHzNXNQJ1CCLsEVIN3XCgCK1I4GVrXW5ymjlf9ajOCKqre-1XBcUOtCZFdbuGIAKyjheZTn0M3IOn8cfTYwmgWb74hOlQLJrh3fhKeMOwEHRJoOG2VQK2_QUM8tFHKkRjK4OJWomo5T1=w296-h202-n-k-no', 47.8100, -123.9351, 1 ),
('Mount Saint Helens', 'Mount St. Helens is an active stratovolcano located in Skamania County, Washington, in the Pacific Northwest region of the United States. It is 50 miles northeast of Portland, Oregon and 96 miles south of Seattle, Washington.', 'https://t2.gstatic.com/images?q=tbn:ANd9GcSBMmzRGcl0cq7sbOL1FfMwIJAjU7dpyyB86botcKxe9cDxrMEa-07KAKY5mOh38YJd-H4a-ecQ4icl10iIMrd2GA', 46.0512, -122.0550, 1 ),
('Mount Baker', 'Mount Baker, also known as Koma Kulshan or simply Kulshan, is a 10,781 ft active glacier-covered andesitic stratovolcano in the Cascade Volcanic Arc and the North Cascades of Washington in the United States.', 'https://t2.gstatic.com/images?q=tbn:ANd9GcSfYQ-8jEiNEoZUfLDOQmb8iYNIzep-dLOEBVG80uvGpqxqnJOAw_uPwt3N0nxTyXUzfMFkLEeHiOCjI-CZiF475w', 48.7555, -121.7777, 1);

INSERT INTO adventure_companies (name, address_1, address_2, city, state, zip_code, phone, email, website, description, image) VALUES ("REI Adventures","222 Yale Ave N","address_2" , "Seattle", "Washington", 98109, 2062231944, "travel@rei.com", "https://www.rei.com/adventures", "Wherever you want to go, whatever you want to get into, we've got a trip that’ll make your dream vacation come true. Visit like a local, explore at your own pace, and eat like a king (or a vegan king, if that's more your thing).", "https://www.rei.com/adventures/assets/adventures/images/trip/core/northamerica/obh_hero");

INSERT INTO company_users (user_name, password, email) VALUES("companyusernameTest", "passwordTest", "companyuser@test.com");

INSERT INTO posts (title, description, image) VALUES("Neah Bay", "Went to Neah Bay because I saw it on this site. Thanks Minnesvart for the reccommendation. I had a great time!", "https://res.cloudinary.com/kaylanewlon/image/upload/v1605425539/kayla_neah_bay_zukt3j.jpg");

INSERT INTO tags(name, description, image) VALUES ("Snowshoeing", "A snowshoe is footwear for walking over snow. Snowshoes work by distributing the weight of the person over a larger area so that the person's foot does not sink completely into the snow, a quality called 'flotation'. Snowshoeing is a form of hiking.","https://res.cloudinary.com/kaylanewlon/image/upload/v1605426083/GOPR0126_yb3vg6.jpg");

-- INSERT INTO users(first_name, last_name, email, username, password, city, state, image, resetPasswordToken, resetPasswordExpires) VALUES ("Kayla", "Newlon", "testuser@email.com", "usernameTest", "Seattle", "Washington","https://res.cloudinary.com/kaylanewlon/image/upload/v1605426391/portfolio_pic_gmwni5.jpg", "123456789" );